# Generated by Django 5.0.6 on 2024-06-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_order_orderitem_order_products_payment_refund_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
